version: "3"
services:
  # front:
  #   image: react-app
  #   stdin_optn: true
  #   ports:
  #    - "3000:3000"
  server:
    image: react-graphql
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mern-app
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
